# Generated by Django 4.1.1 on 2022-09-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('date_of_publication', models.CharField(max_length=200, null=True)),
                ('number_of_pages', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('principal', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('books', models.ManyToManyField(to='students.book')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.school')),
            ],
        ),
    ]
