# Generated by Django 4.1.1 on 2022-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
