# Generated by Django 4.1.1 on 2022-09-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_book_id_remove_school_id_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.book'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.school'),
        ),
    ]
